### ISSUE TITLE
Obtaining bytes used to instantiate Plaintext back

### ISSUE THREAD

**Issue by UMR1352** [IronCoreLabs/recrypt-rs#172]
Hello,
I realized that if I try to invoke `Plaintext::new(<some bytes>)` and then `plaintext.bytes()` the two slices don't match. Plaintext probably needs to encode the input bytes in some way but is it possible somehow to get the original ones back?

**Comment by coltfred** [comment]
@UMR1352 This is only the case when you don't generate a correct plaintext. Plaintext in the context of a proxy re-encryption library is not the same as a plaintext for AES. See https://github.com/IronCoreLabs/recrypt-rs/issues/170#issuecomment-1161788983 and https://github.com/IronCoreLabs/recrypt-rs/issues/125
