### ISSUE TITLE
Consume ed25519-dalek crate 1.0 when released

### ISSUE THREAD

**Issue by ernieturner** [IronCoreLabs/recrypt-rs#19]
In order to publish our WebAssembly bindings, we need to consume the currently unreleased version of the rand crate which will be published as 0.6. There are a number of breaking changes but we've proved that they work so the changes shouldn't be too difficult.

https://github.com/rust-random/rand/issues/520

**Comment by clintfred** [comment]
We are current maintaining a [fork of ed25519-dalek](https://github.com/IronCoreLabs/ed25519-dalek) that is compatible with `rand` ~0.6.  If https://github.com/dalek-cryptography/ed25519-dalek/pull/57 is merged, then we can continue to depend on upstream.

**Comment by coltfred** [comment]
fixed by #43
