### ISSUE TITLE
Add documentation to recrypt (Scala) to talk about state of project and existence of recrypt-rs

### ISSUE THREAD

**Issue by ernieturner** [IronCoreLabs/recrypt-rs#62]
We should mention in the recrypt Scala repo the state of things and how the Rust SDK has somewhat subsumed the Scala repo.

**Comment by BobWall23** [comment]
Issue moved to [IronCoreLabs/recrypt #41](https://github.com/IronCoreLabs/recrypt/issues/41) via [**ZenHub**](https://www.zenhub.com/)
