### ISSUE TITLE
Update to rand 0.7

### ISSUE THREAD

**Issue by clintfred** [IronCoreLabs/recrypt-rs#84]
It would be nice to keep up with new rand versions.

The major hurdle to upgrading is that we have dependencies that [don't want to upgrade](https://github.com/dalek-cryptography/ed25519-dalek/issues/89). 

Perhaps we can [import two different versions of rand](https://github.com/rust-lang/cargo/pull/4953) and re-work things so that recrypt holds a separate RNG for ed25519? It would take some experimentation to see if this is possible.

**Comment by ernieturner** [comment]
Work for this should be an investigation into using multiple different versions of Rand in our project.

**Comment by burdges** [comment]
I implement a wrapper type shim for this in https://github.com/w3f/schnorrkel/commits/schizomerlin

**Comment by clintfred** [comment]
We could upgrade to rand 0.7 is now easier as https://crates.io/crates/ed25519-dalek has released a pre3 that uses rand 0.7.
