### ISSUE TITLE
Serializing the encrypted value?

### ISSUE THREAD

**Issue by drbh** [IronCoreLabs/recrypt-rs#89]
I'm following the single hop example and would like to store the `encrypted_val` in some persisted datastore.

How can I serialized and then deserialize this structure to store on disk and then decrypt later?

Snippet in question
```rust
let encrypted_val = recrypt
    .encrypt(&pt, &initial_pub_key, &signing_keypair)
    .unwrap();
```

**Comment by drbh** [comment]
Also extending my question, how can I serialize the the keys pairs like `initial_priv_key`, `target_pub_key` and the 
`signing_keypair` so I don't generate new ones on each run?

**Comment by clintfred** [comment]
We don't support direct serialization (serde) of top-level recrypt types like keys or encrypted values, although there's no reason that couldn't be added. The underlying types have ways of serializing -- called `bytes()` or `to_bytes()`

See https://github.com/IronCoreLabs/ironoxide/blob/7b10593f90885c69333f13717d52d46f1d641810/src/internal/rest.rs#L537 for an example of using the underlying type's serialization.

**Comment by clintfred** [comment]
We would consider a PR for this, but it's not a priority at this point. The higher-level SDKs (ironoxide, ironweb) provide ways of serializing keys and encrypted data.
